--- 
apiVersion: v1
kind: ReplicationController
metadata: 
  labels: 
    facing: front
    service: flappy
    type: silex
  name: flappy-silex-v1
spec: 
  replicas: 2
  selector: 
    service: flappy
    type: silex
    version: v1
  template:
    metadata: 
      labels: 
        service: flappy
        type: silex
        version: v1
    spec: 
      containers: 
        - 
          image: quay.io/purplebooth/flappy-endpoint
          imagePullPolicy: Always
          livenessProbe: 
            httpGet: 
              path: /
              port: 80
            initialDelaySeconds: 15
            timeoutSeconds: 1
          name: flappy-silex
          ports: 
            - 
              containerPort: 80
              name: http
              protocol: TCP
      restartPolicy: Always
