--- 
apiVersion: v1
kind: Service
metadata: 
  labels: 
    facing: front
    service: flappy
    type: silex
  name: flappy-silex
spec: 
  ports: 
    - 
      name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector: 
    service: flappy
    type: silex
