--- 
apiVersion: v1
kind: ReplicationController
metadata: 
  labels: 
    facing: front
    service: flappy
    type: silex
  name: flappy-silex
spec:
  replicas: 2
  selector:
    name: flappy-silex
  template:
    metadata:
      labels:
        name: flappy-silex
    spec:
      containers:
        -
          image: quay.io/purplebooth/flappy-endpoint
          imagePullPolicy: Always
          name: flappy-silex
          ports:
            -
              containerPort: 80
              name: http
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15
            timeoutSeconds: 1
      restartPolicy: Always
